### ISSUE TITLE
Write Comprehensive Documentation for API

### ISSUE THREAD

**Issue by drakeRAGE** [drakeRAGE/InsightAdmin#3]
The current API for the Admin Dashboard lacks comprehensive documentation, which is essential for developers to understand and use the API effectively. Writing clear and detailed documentation will improve the usability of the API, making it easier for developers to integrate and maintain the system.

**Tasks:**
1. **API Overview:**
   - Provide an overview of the API, including its purpose, key features, and how it fits into the overall architecture of the Admin Dashboard.

2. **Endpoint Documentation:**
   - Document each API endpoint, including:
     - **Endpoint URL:** The specific URL for each endpoint.
     - **HTTP Methods:** The allowed HTTP methods (GET, POST, PUT, DELETE, etc.).
     - **Request Parameters:** Required and optional parameters, including their types and descriptions.
     - **Request Body:** Detailed examples of request payloads for POST and PUT operations.
     - **Response Format:** Examples of successful and error responses, including status codes and payload structure.

3. **Authentication & Authorization:**
   - Explain the authentication process (e.g., JWT tokens) and how to include authorization headers in API requests.
   - Provide examples of how to generate and use tokens.

4. **Error Handling:**
   - Document common error codes and their meanings.
   - Provide guidance on how to handle errors and what to expect in different failure scenarios.

5. **Usage Examples:**
   - Include practical examples of how to use the API for common tasks, such as creating a new user, retrieving user data, updating user information, and deleting a user.
   - Provide code snippets in popular programming languages (e.g., JavaScript, Python) to demonstrate API usage.

6. **Versioning & Updates:**
   - Explain the API versioning strategy and how developers can handle updates or changes to the API.
   - Include a changelog section that documents any changes or updates to the API.

7. **Best Practices:**
   - Offer recommendations on best practices for using the API efficiently and securely.
   - Include tips on optimizing API calls, handling rate limits, and securing sensitive data.

8. **Testing & Tools:**
   - Recommend tools and resources for testing the API, such as Postman or cURL.
   - Include sample requests that developers can use to test API functionality.

9. **Contribution Guidelines:**
   - Provide guidelines for contributing to the API documentation, including how to report issues or suggest improvements.

**Priority:** Medium

**Expected Outcome:**
Comprehensive and easy-to-understand documentation will be created for the API, enabling developers to integrate, use, and maintain the API effectively. This documentation will serve as a valuable resource for current and future development.

---

This issue will help ensure that your API is well-documented, making it easier for developers to work with and maintain.

**Comment by jaketanis** [comment]
Hi @drakeRAGE, I can help with documenting API needs. 

Is there existing documentation for the API that I can refer to?

**Comment by drakeRAGE** [comment]
Hi @seiji-alyosha,

Thank you for offering to help with the documentation. Currently, we don't have any existing documentation for the API. We're starting from scratch, so your assistance in creating comprehensive and detailed documentation would be invaluable.

If you need any specific information or have questions about the API's functionality, feel free to ask. We appreciate your help in improving the usability of our Admin Dashboard API.

Best regards,  
@drakeRAGE

**Comment by jaketanis** [comment]
Sounds great. I will get started on this as soon as I can. I will reach out if I have any questions.

**Comment by jaketanis** [comment]
@drakeRAGE, can you point me to where the code for the API is?

**Comment by Ashleycodesseo** [comment]
Hey @drakeRAGE if you still need help with your documentation let me know. I'm looking to gain some experience and I'd love to help you out
